#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=23:59:00
#PBS -N convert1to25

PROJECTPATH="/home/hpc/capn/mpp460/projects/km3netHdf5ToHistograms/"
echo "PROJECTPATH: $PROJECTPATH"

pip install --user pandas numpy
pwd
cd ${PROJECTPATH}
pwd

time ./doTheConversion1to25.sh

exit 0
