#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=23:59:00
#PBS -N convert76to100

PROJECTPATH="/home/hpc/capn/mpp460/projects/km3netHdf5ToHistograms/"
echo "PROJECTPATH: $PROJECTPATH"

pip install --user pandas numpy

cd ${PROJECTPATH}
time ./doTheConversion76to100.sh

exit 0
