#!/bin/bash -l
#PBS -l nodes=1:ppn=4,walltime=23:59:00
#PBS -N numu2_h5ToH

PROJECTPATH="/home/hpc/capn/mpp460/projects/km3netHdf5ToHistograms/"
echo "PROJECTPATH: $PROJECTPATH"

pip install --user pandas numpy

cd ${PROJECTPATH}
for i in {51..100}; do
time python h5ToHistograms.py hdf5files/km3_v4_numuCC_${i}.JTE_r2356.root.h5
done

exit 0
